apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-qa
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: CreateNamespace=true

spec:
  project: default

  source:
    repoURL: https://github.com/ThanujaRatakonda/kp_11
    targetRevision: master
    path: backend-hc
    helm:
      valueFiles:
        - backendvalues_qa.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: qa

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
