apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: CreateNamespace=true

spec:
  project: default

  source:
    repoURL: https://github.com/ThanujaRatakonda/kp_9
    targetRevision: master
    path: frontend-hc
    helm:
      valueFiles:
        - frontendvalues_pro.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: pro

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
